import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MainHeader from "@/components/Header/mainHeader";
import MainFooter from "@/components/Footer/mainFooter";
import PriceHeader from "@/components/Header/PriceHeader";
import ConnectFooter from "@/components/Footer/connect";
import AppProvider from "@/Providers/appProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppProvider>
          <MainHeader />
          {children}
          <MainFooter />
          <ConnectFooter />
        </AppProvider>
      </body>
    </html>
  );
}
